# This srv file defines the servce
# for a single motion planning query
# given the updated object pose and robot grasp pose

geometry_msgs/Pose[] grasp_pose_candidates
geometry_msgs/Pose bbox_pose
float32[] bbox_dims
---
bool success
